// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvaT5cb4SPJkI24eG6qCzLsR2y86AtgJw',
    appId: '1:675670966173:web:56968ab09293661282f974',
    messagingSenderId: '675670966173',
    projectId: 'arcohol-20250609',
    authDomain: 'arcohol-20250609.firebaseapp.com',
    storageBucket: 'arcohol-20250609.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCcQzPkM3o2DCftCtVnq4x7SAZvdWYX8w',
    appId: '1:675670966173:android:13fc2b130c04080382f974',
    messagingSenderId: '675670966173',
    projectId: 'arcohol-20250609',
    storageBucket: 'arcohol-20250609.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDt0RIO4QqUnKfM9NYemitffkO3yUUvBM0',
    appId: '1:675670966173:ios:a580b67c2affa8df82f974',
    messagingSenderId: '675670966173',
    projectId: 'arcohol-20250609',
    storageBucket: 'arcohol-20250609.firebasestorage.app',
    iosBundleId: 'com.example.arcohol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDt0RIO4QqUnKfM9NYemitffkO3yUUvBM0',
    appId: '1:675670966173:ios:a580b67c2affa8df82f974',
    messagingSenderId: '675670966173',
    projectId: 'arcohol-20250609',
    storageBucket: 'arcohol-20250609.firebasestorage.app',
    iosBundleId: 'com.example.arcohol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvaT5cb4SPJkI24eG6qCzLsR2y86AtgJw',
    appId: '1:675670966173:web:51a095fdc3fa33d182f974',
    messagingSenderId: '675670966173',
    projectId: 'arcohol-20250609',
    authDomain: 'arcohol-20250609.firebaseapp.com',
    storageBucket: 'arcohol-20250609.firebasestorage.app',
  );
}
